In [20]:
import numpy as np
import math
size=str(input("Please input the size of the mask Eg:5x5,3x3, other sizes? :" ))
size=size[0]
size=int(size)
mask =  np.fromfunction(lambda x, y: (1/(2*math.pi*1**2)) * math.e **((-1*((x-(size-1)/2)**2+(y-(size-1)/2)**2))/(2*1**2)),(size, size))
print("THIS IS THE MASK THAT WOULD BE APPLIED TO THE IMAGE")
mask_k=mask / np.sum(mask)
print(np.array(mask_k))
Image=str(input("Please specify the size of the Image :"))
yes="10x10"
Row=Image.split("x")[0]
Column=Image.split("x")[-1]
a=yes.split("x")[0]
Row=int(Row)
Column=int(Column)
image=np.random.rand(Row,Column)
print("THIS IS THE IMAGE THAT THE MASK WILL BE APPLIED ON")
print(np.array(image))
scope = int((size-1)/2)
gaussianFilter = np.zeros((image.shape[0]-2*scope, image.shape[1]-2*scope))
for y in range(scope, image.shape[0]-scope):
    for x in range(scope, image.shape[1]-scope):
        gaussianFilter[y-scope][x-scope] = np.sum(np.multiply(image[y-scope:y+scope+1, x-scope:x+scope+1], mask_k))
print("THIS IS THE IMAGE AFTER THE MASK HAS BEEN APPLIED ON IT")
(np.array(gaussianFilter))




Please input the size of the mask Eg:5x5,3x3, other sizes? :3x3
THIS IS THE MASK THAT WOULD BE APPLIED TO THE IMAGE
[[0.07511361 0.1238414  0.07511361]
 [0.1238414  0.20417996 0.1238414 ]
 [0.07511361 0.1238414  0.07511361]]
Please specify the size of the Image :5x5
THIS IS THE IMAGE THAT THE MASK WILL BE APPLIED ON
[[0.84863045 0.03442078 0.7818251  0.87151162 0.41999877]
 [0.15625242 0.0944267  0.44448041 0.82926766 0.84210662]
 [0.9822678  0.17808216 0.13318721 0.70220828 0.4567458 ]
 [0.46103004 0.29160186 0.96785571 0.43290368 0.30839661]
 [0.00903355 0.78378569 0.01548782 0.18343102 0.7193916 ]]
THIS IS THE IMAGE AFTER THE MASK HAS BEEN APPLIED ON IT


array([[0.32624755, 0.45263165, 0.65812958],
       [0.37475861, 0.43491849, 0.56524817],
       [0.44124127, 0.44452557, 0.45563339]])